### PR TITLE
added dockerfiles for the quasar youtube tutorial based on public available docker hubs 

### PR DESCRIPTION
**Pull request by upohl**
added dockerfiles for the quasar youtube tutorial based on public available docker hubs . 
(https://www.youtube.com/channel/UCQdLb4N-CEWrpYROcC-UF6w)
- one folder for open62541 on the basis of ubuntu 
- one folder for unified automation on the basis of debian wheezy

### CODE REVIEW

**Comment by ben-farnham** [comment]
Hello Uwe,

Welcome, and thanks for your pull request - sorry it took me a while to around to processing them: I've been rather distracted by other work for a few weeks but I'm back from all that now.

The additions you propose look fine to me, just before I approve and merge them though I'd be very interested to know something about the context, mainly out of curiosity and also to understand what you are using quasar for etc.

Cheers,
Ben

**Comment by upohl** [comment]
Hi Ben,
A couple of month ago we had a call with
Michael Ludwig <Michael.Ludwig@cern.ch<mailto:Michael.Ludwig@cern.ch>>, Pascal Oser <p.oser@cern.ch<mailto:p.oser@cern.ch>>, "Enrique Blanco Vinuela" <Enrique.Blanco@cern.ch<mailto:Enrique.Blanco@cern.ch>>, Fernando Varela Rodriguez <Fernando.Varela.Rodriguez@cern.ch<mailto:Fernando.Varela.Rodriguez@cern.ch>>, about OPC UA and security.
They mentioned to they use quasar and I would like to have a look which default security configurations quasar generates.
As a starting point, I used your youtube video but it took me a while to get it running due to wrong or missing dependencies.
Therefore, I created the docker files to make it easier to run your tutorial.
Unfortunately<https://www.dict.cc/englisch-deutsch/unfortunately.html>, the default security configuration is completely open and using the 0.2 Version of open62451 security is not implemented at all.

We recently publish a first rather non-technical whitepaper about using OPC UA securely (https://opcfoundation.org/security) in cooperation with the opc foundation.
I’m the chairman of this OPC UA Security User Group.
Next year, I’d like to develop and publish best practices and use cases for using OPC UA in a secure way in another whitepaper as I guess many people are struggling currently using it securely.


I saw that you spent time to summaries the OPC UA security capabilities.
https://readthedocs.web.cern.ch/display/ICKB/Security

Is the CERN an OPCF member?
If this is the case, I’d like to invite you to participate within our user group and may provide a description of using OPC UA in combination with Kerberos and LDAP.

Are you interested?

Best regards,
Uwe


Von: Ben Farnham [mailto:notifications@github.com]
Gesendet: Mittwoch, 6. Dezember 2017 17:36
An: quasar-team/docker <docker@noreply.github.com>
Cc: Uwe Pohlmann <upohl@upb.de>; Author <author@noreply.github.com>
Betreff: Re: [quasar-team/docker] added dockerfiles for the quasar youtube tutorial based on public available docker hubs (#1)


Hello Uwe,

Welcome, and thanks for your pull request - sorry it took me a while to around to processing them: I've been rather distracted by other work for a few weeks but I'm back from all that now.

The additions you propose look fine to me, just before I approve and merge them though I'd be very interested to know something about the context, mainly out of curiosity and also to understand what you are using quasar for etc.

Cheers,
Ben

**Comment by ben-farnham** [comment]
Hi Uwe,

Yes, CERN is a member of the OPCF (not a corporate member; CERN is a not a commercial organisation). As you mention, I did some investigation a while ago into how OPC-UA client/server components could be secured and I'd be very interested to participate in the user group you mention - to share ideas on how best to secure OPC-UA infrastructure whilst imposing as little administrative overhead as possible. So, thanks for the invite - please let me know what's next.

Cheers,
Ben

**Comment by upohl** [comment]
Hi Ben, that sounds great.
I will add you to our sharepoint server and mailing list.
The group will be relaunched in the beginning of next year and I will send you an invitation to our telefon call, when it is scheduled.

Regards,
Uwe


Von: Ben Farnham [mailto:notifications@github.com]
Gesendet: Donnerstag, 7. Dezember 2017 16:16
An: quasar-team/docker <docker@noreply.github.com>
Cc: Uwe Pohlmann <upohl@upb.de>; Author <author@noreply.github.com>
Betreff: Re: [quasar-team/docker] added dockerfiles for the quasar youtube tutorial based on public available docker hubs (#1)


Hi Uwe,

Yes, CERN is a member of the OPCF (not a corporate member; CERN is a not a commercial organisation). As you mention, I did some investigation a while ago into how OPC-UA client/server components could be secured and I'd be very interested to participate in the user group you mention - to share ideas on how best to secure OPC-UA infrastructure whilst imposing as little administrative overhead as possible. So, thanks for the invite - please let me know what's next.

Cheers,
Ben

**Pull request merged**
