### PR TITLE
updated dockerfile for unified automation v1.5.6

### PR DESCRIPTION
**Pull request by ben-farnham**
also changed the image build process a bit: Now builds the unified auomation toolkit from source when building the image

### CODE REVIEW

**Comment by ben-farnham** [comment]
Hi All,

Anyone interested in reviewing the changes in the dockerfile used to build the image for CC7, with the Unified Automation SDK?

Naturally, since the SDK is commercial then the resulting images built using this dockerfile cannot be made public.

Was also thinking it's a fairly easy modification/extension to this dockerfile to be have the capability to build images using the Unified Automation time-limited trial SDKs. But that's another story for another PR.

Cheers,
Ben

**Comment by pnikiel** [comment]
Hi Ben,
had a 2-minute look. Looks sane, perhaps worth asking what features you get from custom boost which you can't get from CC7-standard boost 1.53?
I.e. if we can build CAEN and Iseg server with standard CC7 boost then why you wouldn't?

But that's rather out of curiosity question. Probably we are not considered target customers of those builds.

**Comment by ben-farnham** [comment]
Thanks Piotr. 

Background to this is I build the gitlab-ci docker image from this dockerfile, and then gitlab-ci runs its CI build, test, package on this image. Custom boost BTW is for the LogIt backend for the Boost rotating log library. It has only been a part of boost since 1.54, annoyingly.

Cheers

**Comment by ben-farnham** [comment]
Meant to add to above this is for gitlab-ci for the caen-opcua-server (and, once that's working, also the iseg-opcua-server).

So, yes - ATLAS is not a direct customer since you build your own.

**Pull request merged**
