### PR TITLE
updated linux CI image

### PR DESCRIPTION
**Pull request by ben-farnham**
This PR  is a sub-component of quasar PR https://github.com/quasar-team/quasar/pull/213 (contains changes to CI linux build regarding docker)

### CODE REVIEW

**Comment by pnikiel** [comment]
I think it's quite sensible.
What also comes to my mind (is kind of optional though and up to you) is also getting pygit2 as it's "kind of standard" in quasar to stamp the builds with commit id.

**Comment by parasxos** [comment]
For pygit2 it seems there is no package as for the other dependancies (at least for CentOS) and for that I was using pip3 to install it.

**Comment by pnikiel** [comment]
Hi Paris, 
the images are based on Ubuntu; just checked: it's there as "python3-pygit2".

**Review by parasxos — APPROVED** [review]
except for what I added it looks fine

**Comment by ben-farnham** [comment]
Hi folks, thanks for the comments. In this instance I'll pass on the opportunity to add pygit2: My approach is always to avoid complexity wherever possible. So, if it's currently not a concrete requirement I'll omit it for now (we can extend the image if/when it becomes such).

Cheers,
Ben

**Pull request merged**
